"$schema" = 'https://starship.rs/config-schema.json'

format = "$time $directory$git_branch$git_status$cmd_duration$line_break$character"

[directory]
truncation_length = 1024
truncation_symbol = '…/'
truncate_to_repo = false
read_only = ''

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M:%S"
