"$schema" = 'https://starship.rs/config-schema.json'

format = "$time $directory"

[directory]
truncation_length = 1024
truncation_symbol = '…/'
truncate_to_repo = false
read_only = ''

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M:%S"
