[window]
decorations = "None"
padding = { x = 5, y = 5 }

# Set default window size (in columns and lines)
dimensions = { columns = 160, lines = 48 }

# Alternatively, you could set pixel size instead:
# size = { width = 1600, height = 900 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 11.0
